# Databases and  aws resources

services:

  localstack:
    container_name: localstack
    image: localstack/localstack:3.6
    ports:
      - 4563-4599:4563-4599
      - 8055:8080
    environment:
      - SERVICES=dynamodb,kms,s3
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PERSISTENCE=1
      - DYNAMODB_SHARE_DB=1
    volumes:
      #- ./storage-service/create-aws-data.sh:/etc/localstack/init/ready.d/init-aws.sh
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  neo4j:
    container_name: neo4j
    image: neo4j:5.16-community-bullseye
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data/
  
volumes:
  neo4j_data:
  localstack_data:
  